name: citygml-tools-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ "macos-latest", "ubuntu-latest", "windows-latest" ]
        distribution: [ "temurin" ]
        version: [ "11" ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-disabled: true